---
- name: Create backup keypair
  openssh_keypair:
    path: "/root/.ssh/{{ backups_sh_key_filename }}"
    type: rsa

- name: Install backupninja package
  package:
    name: backupninja
    use: apt
    state: present

- name: Setup backupninja config for docker data
  ansible.builtin.template:
    src: ./templates/backupninja_rsync.conf
    dest: "{{ backup_confs_dir  }}/docker_data.conf"
    owner: root
    group: root
