- name: Dokuwiki group
  group:
    name: dokuwiki
    state: present
    gid: "{{ gid }}"

- name: Dokuwiki user
  user:
    name: dokuwiki
    state: present
    uid: "{{ uid }}"
    group: dokuwiki

- name: Create the configuration directory
  file:
     path: '{{ docker_dir }}/{{ container_name }}'
     state: directory
     recurse: yes
     owner: dokuwiki
     group: dokuwiki
     mode: "770"

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: "{{ container_name }}"
    image: lscr.io/linuxserver/dokuwiki:latest
    state: 'started'
    env:
      PUID: "{{ uid  }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      VIRTUAL_HOST: "{{ ansible_hostname }}.local,{{ public_domain }}"
      VIRTUAL_PATH: "/wiki/"
      VIRTUAL_DEST: "/"
      VIRTUAL_PORT: "80"
    volumes:
      - '{{ docker_dir }}/{{ container_name }}:/config'
    exposed:
      - '80'
    restart_policy: unless-stopped

- name: Install {{ template_name }} template archive
  unarchive:
    src: https://github.com/saschaleib/dokuwiki-template-ad-hominem/archive/refs/tags/{{ template_release }}.tar.gz
    dest: "{{ docker_dir }}/{{ container_name }}/dokuwiki/lib/tpl"
    remote_src: yes
    creates: "dokuwiki-template-{{ template_name }}-{{ template_release }}"
    owner: dokuwiki
    group: dokuwiki

- name: Set the dokuwiki template to {{ template_name }}
  lineinfile:
    path: "{{ docker_dir }}/{{ container_name }}/dokuwiki/conf/dokuwiki.php"
    search_string: "$conf['template']"
    line: "$conf['template']    = 'dokuwiki-template-{{ template_name }}-{{ template_release }}'; "

- name: Set the dokuwiki title
  lineinfile:
    path: "{{ docker_dir }}/{{ container_name }}/dokuwiki/conf/dokuwiki.php"
    search_string: "$conf['title']"
    line: "$conf['title']    = 'Mojo Manor';"