- name: Dokuwiki group
  group:
    name: dokuwiki
    state: present
    gid: "{{ gid }}"

- name: Dokuwiki user
  user:
    name: dokuwiki
    state: present
    uid: "{{ uid }}"
    group: dokuwiki

- name: Create the configuration directory
  file:
     path: '{{ docker_dir }}/{{ container_name }}'
     state: directory
     recurse: yes
     owner: dokuwiki
     group: dokuwiki
     mode: "770"

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
     name: "{{ container_name }}"
     image: lscr.io/linuxserver/dokuwiki:latest
     state: 'started'
     env:
        PUID: "{{ uid  }}"
        PGID: "{{ gid }}"
        TZ: "{{ timezone }}"
     volumes:
        - '{{ docker_dir }}/{{ container_name }}:/config'
     ports:
        - '80:80'
     restart_policy: unless-stopped

- name: Install {{ template_name }} template archive
  unarchive:
    src: https://github.com/saschaleib/dokuwiki-template-ad-hominem/archive/refs/tags/{{ template_release }}.tar.gz
    dest: "{{ docker_dir }}/{{ container_name }}/dokuwiki/lib/tpl"
    remote_src: yes
    creates: "dokuwiki-template-{{ template_name }}-{{ template_release }}"
    owner: dokuwiki
    group: dokuwiki
    mode: "440"

- name: Create a symbolic link to template
  file:
    src: "{{ docker_dir }}/{{ container_name }}/dokuwiki/lib/tpl/dokuwiki-template-{{ template_name }}-{{ template_release }}"
    dest: "{{ docker_dir }}/{{ container_name }}/dokuwiki/lib/tpl/{{ template_name }}"
    owner: dokuwiki
    group: dokuwiki
    state: link