- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: "{{ container_name }}"
    image: redbugcollective/pibasho-frontend:v0.1.23
    state: 'started'
    restart_policy: unless-stopped
    exposed:
      - '80'
    env:
      VIRTUAL_HOST: "{{ ansible_hostname }}.local"
      VIRTUAL_PATH: "/{{ base_path }}/"
      VIRTUAL_PORT: "80"